name: "b_project"
type: "python: 3.12"

relationships: 
  database: "db:postgresql"

# Configuraci칩n de la app cuando se expone a la web
web:
  upstream:
    socket_family: "unix"
  commands:
    start: "guicorn -w 4 -b unix:$SOCKET b_project.wsgi:application"
  locations:
    "/":
      passthrough: true
    "/static": Styling and deploying an App
      root: "static"
      expires: 1h
      allow: true

# Tama침o del disco pwrsistente de la aplicaci칩n (en MB).
disk: 512

# Establece un modelo local de lectura y escritura para los registros.
mounts:
  "logs":
    source: "local"
    source_path: "logs"

# Hooks ejecutados en varios puntos del ciclo de vida de la aplicaci칩n.
hooks:
  build: |
    pip install --upgrade pip
    pip install -r requirements.txt
    pip install -r requirements_remote.txt

    mkdir logs
    python manage.py collectstatic
    rm -rf logs
  deploy: |
    python manage.py migrate