# Generated by Django 5.0.3 on 2024-03-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='title',
            field=models.CharField(default='Sin título', max_length=100),
        ),
    ]
