# Generated by Django 5.0.3 on 2024-03-23 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pizza',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
