lugares = ["polonia", "república dominicana", "maldivas", "parís", "toscana italiana", "islas griegas"]
print("Lista original:")
print(lugares)
print("Lista ordenada alfabéticamente:")
print(sorted(lugares))
print("Lista original otra vez:")
print(lugares)
print("Lista ordenada alfabéticamente de forma inversa:")
print(sorted(lugares, reverse=True))
print("Lista original otra vez:")
print(lugares)
lugares.reverse()
print("Lista original ordenada de manera inversa:")
print(lugares)
lugares.reverse()
print("Lista anterior ordenada de manera inversa:")
print(lugares)
lugares.sort()
print("Lista ordenada alfabéticamente:")
print(lugares)
lugares.sort(reverse=True)
print("Invertimos la lista anterior:")
print(lugares)